site_name: LinkML Toolkit
site_description: A comprehensive toolkit for working with LinkML schemas
site_author: Your Name
site_url: https://github.com/yourusername/linkml-toolkit

repo_name: yourusername/linkml-toolkit
repo_url: https://github.com/yourusername/linkml-toolkit

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          selection:
            docstring_style: google

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
      - Getting Started: usage/getting-started.md
      - Schema Summary: usage/summary.md
      - Schema Validation: usage/validation.md
      - Merging Schemas: usage/merge.md
      - Concatenating Schemas: usage/concat.md
      - Exporting Schemas: usage/export.md
  - API Reference:
      - Core: api/core.md
      - Validation: api/validation.md
      - Export: api/export.md
      - CLI: api/cli.md
  - Contributing: contributing.md
